exp_name: hete_mese_paper_dblp_2_paper_metric_fix_50

dataset: DBLP

center_type: paper

meta_paths:
  P-A-P: 1.0
  P-T-P: 1.0
  P-C-P: 1.0
  # A-P-A: 1.0
  # # A-P-T-P-A: 1.0
  # A-P-C-P-A: 1.0

thresholds:
  P-A-P: 1
  P-T-P: 5
  P-C-P: 1
  # A-P-A: 2
  # # A-P-T-P-A: 1
  # A-P-C-P-A: 50

consensus:

  min_agree: 1

  normalize: all_layers

expansion:

  stable: false